version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: todo-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TMPDIR=/tmp/localstack-tmp
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  migrate:
    image: migrate/migrate
    container_name: todo-migrate
    volumes:
      - ./infrastructure/migration:/migrations
    command: [ "-path", "/migrations", "-database", "mysql://root:password@tcp(mysql:3306)/todo_db", "up" ]
    depends_on:
      mysql:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - AWS_ENDPOINT=http://localstack:4566
    ports:
      - "8080:8080"

volumes:
  mysql-data:
  redis-data: