// Code generated by MockGen. DO NOT EDIT.
// Source: ../domain/repository/stream_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStreamRepository is a mock of StreamRepository interface.
type MockStreamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStreamRepositoryMockRecorder
}

// MockStreamRepositoryMockRecorder is the mock recorder for MockStreamRepository.
type MockStreamRepositoryMockRecorder struct {
	mock *MockStreamRepository
}

// NewMockStreamRepository creates a new mock instance.
func NewMockStreamRepository(ctrl *gomock.Controller) *MockStreamRepository {
	mock := &MockStreamRepository{ctrl: ctrl}
	mock.recorder = &MockStreamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamRepository) EXPECT() *MockStreamRepositoryMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockStreamRepository) Publish(streamName string, data map[string]interface{}) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", streamName, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockStreamRepositoryMockRecorder) Publish(streamName, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockStreamRepository)(nil).Publish), streamName, data)
}
