// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase/stream_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStreamUseCaseInterface is a mock of StreamUseCaseInterface interface.
type MockStreamUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStreamUseCaseInterfaceMockRecorder
}

// MockStreamUseCaseInterfaceMockRecorder is the mock recorder for MockStreamUseCaseInterface.
type MockStreamUseCaseInterfaceMockRecorder struct {
	mock *MockStreamUseCaseInterface
}

// NewMockStreamUseCaseInterface creates a new mock instance.
func NewMockStreamUseCaseInterface(ctrl *gomock.Controller) *MockStreamUseCaseInterface {
	mock := &MockStreamUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockStreamUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamUseCaseInterface) EXPECT() *MockStreamUseCaseInterfaceMockRecorder {
	return m.recorder
}

// GetStreamData mocks base method.
func (m *MockStreamUseCaseInterface) GetStreamData(streamName string, count int64, start string) ([]map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamData", streamName, count, start)
	ret0, _ := ret[0].([]map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamData indicates an expected call of GetStreamData.
func (mr *MockStreamUseCaseInterfaceMockRecorder) GetStreamData(streamName, count, start interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamData", reflect.TypeOf((*MockStreamUseCaseInterface)(nil).GetStreamData), streamName, count, start)
}
