// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase/todo_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	entity "github.com/ahmadrezamusthafa/ice-todo-service/domain/entity"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTodoUseCaseInterface is a mock of TodoUseCaseInterface interface.
type MockTodoUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTodoUseCaseInterfaceMockRecorder
}

// MockTodoUseCaseInterfaceMockRecorder is the mock recorder for MockTodoUseCaseInterface.
type MockTodoUseCaseInterfaceMockRecorder struct {
	mock *MockTodoUseCaseInterface
}

// NewMockTodoUseCaseInterface creates a new mock instance.
func NewMockTodoUseCaseInterface(ctrl *gomock.Controller) *MockTodoUseCaseInterface {
	mock := &MockTodoUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockTodoUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoUseCaseInterface) EXPECT() *MockTodoUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoUseCaseInterface) CreateTodo(todo *entity.TodoItem) (*entity.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", todo)
	ret0, _ := ret[0].(*entity.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoUseCaseInterfaceMockRecorder) CreateTodo(todo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoUseCaseInterface)(nil).CreateTodo), todo)
}

// DeleteTodo mocks base method.
func (m *MockTodoUseCaseInterface) DeleteTodo(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoUseCaseInterfaceMockRecorder) DeleteTodo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoUseCaseInterface)(nil).DeleteTodo), id)
}

// GetAllTodos mocks base method.
func (m *MockTodoUseCaseInterface) GetAllTodos() ([]*entity.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTodos")
	ret0, _ := ret[0].([]*entity.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTodos indicates an expected call of GetAllTodos.
func (mr *MockTodoUseCaseInterfaceMockRecorder) GetAllTodos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTodos", reflect.TypeOf((*MockTodoUseCaseInterface)(nil).GetAllTodos))
}

// GetTodoByID mocks base method.
func (m *MockTodoUseCaseInterface) GetTodoByID(id uuid.UUID) (*entity.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoByID", id)
	ret0, _ := ret[0].(*entity.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoByID indicates an expected call of GetTodoByID.
func (mr *MockTodoUseCaseInterfaceMockRecorder) GetTodoByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoByID", reflect.TypeOf((*MockTodoUseCaseInterface)(nil).GetTodoByID), id)
}

// UpdateTodo mocks base method.
func (m *MockTodoUseCaseInterface) UpdateTodo(id uuid.UUID, todo *entity.TodoItem) (*entity.TodoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", id, todo)
	ret0, _ := ret[0].(*entity.TodoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoUseCaseInterfaceMockRecorder) UpdateTodo(id, todo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoUseCaseInterface)(nil).UpdateTodo), id, todo)
}
