// Code generated by MockGen. DO NOT EDIT.
// Source: ../usecase/file_usecase.go

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileUseCaseInterface is a mock of FileUseCaseInterface interface.
type MockFileUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFileUseCaseInterfaceMockRecorder
}

// MockFileUseCaseInterfaceMockRecorder is the mock recorder for MockFileUseCaseInterface.
type MockFileUseCaseInterfaceMockRecorder struct {
	mock *MockFileUseCaseInterface
}

// NewMockFileUseCaseInterface creates a new mock instance.
func NewMockFileUseCaseInterface(ctrl *gomock.Controller) *MockFileUseCaseInterface {
	mock := &MockFileUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockFileUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUseCaseInterface) EXPECT() *MockFileUseCaseInterfaceMockRecorder {
	return m.recorder
}

// GetFile mocks base method.
func (m *MockFileUseCaseInterface) GetFile(fileID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", fileID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFileUseCaseInterfaceMockRecorder) GetFile(fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFileUseCaseInterface)(nil).GetFile), fileID)
}

// UploadFile mocks base method.
func (m *MockFileUseCaseInterface) UploadFile(fileName string, fileSize int64, fileContent io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", fileName, fileSize, fileContent)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileUseCaseInterfaceMockRecorder) UploadFile(fileName, fileSize, fileContent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileUseCaseInterface)(nil).UploadFile), fileName, fileSize, fileContent)
}
