// Code generated by MockGen. DO NOT EDIT.
// Source: ../adapter/persistence/s3/file_repository.go

// Package mock_s3_adapter is a generated GoMock package.
package mock_s3_adapter

import (
	io "io"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go/service/s3"
	s3manager "github.com/aws/aws-sdk-go/service/s3/s3manager"
	gomock "github.com/golang/mock/gomock"
)

// MockUploaderInterface is a mock of UploaderInterface interface.
type MockUploaderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderInterfaceMockRecorder
}

// MockUploaderInterfaceMockRecorder is the mock recorder for MockUploaderInterface.
type MockUploaderInterfaceMockRecorder struct {
	mock *MockUploaderInterface
}

// NewMockUploaderInterface creates a new mock instance.
func NewMockUploaderInterface(ctrl *gomock.Controller) *MockUploaderInterface {
	mock := &MockUploaderInterface{ctrl: ctrl}
	mock.recorder = &MockUploaderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploaderInterface) EXPECT() *MockUploaderInterfaceMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploaderInterface) Upload(input *s3manager.UploadInput, options ...func(*s3manager.Uploader)) (*s3manager.UploadOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	ret0, _ := ret[0].(*s3manager.UploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploaderInterfaceMockRecorder) Upload(input interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploaderInterface)(nil).Upload), varargs...)
}

// MockDownloaderInterface is a mock of DownloaderInterface interface.
type MockDownloaderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderInterfaceMockRecorder
}

// MockDownloaderInterfaceMockRecorder is the mock recorder for MockDownloaderInterface.
type MockDownloaderInterfaceMockRecorder struct {
	mock *MockDownloaderInterface
}

// NewMockDownloaderInterface creates a new mock instance.
func NewMockDownloaderInterface(ctrl *gomock.Controller) *MockDownloaderInterface {
	mock := &MockDownloaderInterface{ctrl: ctrl}
	mock.recorder = &MockDownloaderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloaderInterface) EXPECT() *MockDownloaderInterfaceMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockDownloaderInterface) Download(w io.WriterAt, input *s3.GetObjectInput, options ...func(*s3manager.Downloader)) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{w, input}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Download", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockDownloaderInterfaceMockRecorder) Download(w, input interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{w, input}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockDownloaderInterface)(nil).Download), varargs...)
}
