// Code generated by MockGen. DO NOT EDIT.
// Source: ../adapter/persistence/redis/stream_repository.go

// Package mock_redis_adapter is a generated GoMock package.
package mock_redis_adapter

import (
	context "context"
	reflect "reflect"

	redis "github.com/go-redis/redis/v8"
	gomock "github.com/golang/mock/gomock"
)

// MockStreamInterface is a mock of StreamInterface interface.
type MockStreamInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStreamInterfaceMockRecorder
}

// MockStreamInterfaceMockRecorder is the mock recorder for MockStreamInterface.
type MockStreamInterfaceMockRecorder struct {
	mock *MockStreamInterface
}

// NewMockStreamInterface creates a new mock instance.
func NewMockStreamInterface(ctrl *gomock.Controller) *MockStreamInterface {
	mock := &MockStreamInterface{ctrl: ctrl}
	mock.recorder = &MockStreamInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamInterface) EXPECT() *MockStreamInterfaceMockRecorder {
	return m.recorder
}

// XAdd mocks base method.
func (m *MockStreamInterface) XAdd(ctx context.Context, a *redis.XAddArgs) *redis.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XAdd", ctx, a)
	ret0, _ := ret[0].(*redis.StringCmd)
	return ret0
}

// XAdd indicates an expected call of XAdd.
func (mr *MockStreamInterfaceMockRecorder) XAdd(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XAdd", reflect.TypeOf((*MockStreamInterface)(nil).XAdd), ctx, a)
}

// XRead mocks base method.
func (m *MockStreamInterface) XRead(ctx context.Context, a *redis.XReadArgs) *redis.XStreamSliceCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XRead", ctx, a)
	ret0, _ := ret[0].(*redis.XStreamSliceCmd)
	return ret0
}

// XRead indicates an expected call of XRead.
func (mr *MockStreamInterfaceMockRecorder) XRead(ctx, a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XRead", reflect.TypeOf((*MockStreamInterface)(nil).XRead), ctx, a)
}
